version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 8888:8000
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: postgres:14
    container_name: laravel_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network
      

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:


